import type { PipelineV2Agent, PipelineV2AgentDefinition, PipelineV2HistoryPolicy } from '../../models/agent-pipeline-v2.models.js';

const defaultHistory: PipelineV2HistoryPolicy = {
  enabled: true,
  windows: ['recent', 'mid', 'long', 'summary'],
  maxEntries: 100,
  summarizeAfterEntries: 30,
};

export const PIPELINE_V2_AGENT_IDS: PipelineV2Agent[] = [
  'lead-agent',
  'storage-memory-agent',
  'history-agent',
  'search-agent',
  'recommendation-agent',
  'cart-agent',
  'rag-agent',
  'security-agent',
  'customer-support-agent',
  'sales-agent',
];

export const PIPELINE_V2_AGENT_REGISTRY: Record<PipelineV2Agent, PipelineV2AgentDefinition> = {
  'lead-agent': {
    id: 'lead-agent',
    displayName: 'Lead Agent',
    role: 'Analyzes the request deeply, asks the right specialist agents, verifies their answers, and decides the final handoff.',
    owns: ['routing', 'task decomposition', 'answer verification', 'final approval'],
    canReceiveFrom: ['lead-agent'],
    canDelegateTo: ['storage-memory-agent', 'history-agent', 'search-agent', 'recommendation-agent', 'cart-agent', 'rag-agent', 'security-agent', 'customer-support-agent', 'sales-agent'],
    reads: ['in_memory', 'postgres'],
    writes: ['in_memory'],
    history: { ...defaultHistory, maxEntries: 200, summarizeAfterEntries: 40 },
    responseContract: ['intent', 'tasks', 'agent_briefs', 'verification_notes', 'final_handoff'],
    trace: { iconKey: 'route', shortCode: 'L', nodeKind: 'agent' },
  },
  'storage-memory-agent': {
    id: 'storage-memory-agent',
    displayName: 'Storage/Memory Agent',
    role: 'Owns durable user memory and decides when history resolution is needed for ambiguous requests.',
    owns: ['user memory', 'preferences', 'behavior signals', 'memory summaries'],
    canReceiveFrom: ['lead-agent'],
    canDelegateTo: ['history-agent'],
    reads: ['postgres'],
    writes: ['postgres'],
    history: { ...defaultHistory, maxEntries: 160 },
    responseContract: ['memory_brief', 'preference_signals', 'history_needed', 'storage_actions'],
    trace: { iconKey: 'database', shortCode: 'M', nodeKind: 'agent' },
  },
  'history-agent': {
    id: 'history-agent',
    displayName: 'History Agent',
    role: 'Resolves vague references by reading near, mid, long, and summarized conversation history.',
    owns: ['reference resolution', 'recent turns', 'mid history', 'long summary'],
    canReceiveFrom: ['lead-agent', 'storage-memory-agent'],
    canDelegateTo: [],
    reads: ['postgres'],
    writes: ['postgres'],
    history: { ...defaultHistory, maxEntries: 180, summarizeAfterEntries: 25 },
    responseContract: ['resolved_references', 'evidence_turns', 'confidence', 'missing_context'],
    trace: { iconKey: 'history', shortCode: 'H', nodeKind: 'agent' },
  },
  'search-agent': {
    id: 'search-agent',
    displayName: 'Search Agent',
    role: 'Searches products with exact SQL, hard keyword facets, related-family expansion, and candidate validation.',
    owns: ['exact product search', 'hard keyword search', 'related-family expansion', 'candidate validation'],
    canReceiveFrom: ['lead-agent'],
    canDelegateTo: ['recommendation-agent'],
    reads: ['postgres'],
    writes: ['postgres'],
    history: { ...defaultHistory, maxEntries: 120 },
    responseContract: ['search_mode', 'exact_found', 'family_scope', 'candidates', 'reasoning'],
    trace: { iconKey: 'search', shortCode: 'S', nodeKind: 'agent' },
  },
  'recommendation-agent': {
    id: 'recommendation-agent',
    displayName: 'Recommendation Agent',
    role: 'Recommends products by reviewing search candidates, user intent, behavior signals, and sales fit.',
    owns: ['candidate review', 'personalized recommendation', 'bundle suggestions', 'display eligibility'],
    canReceiveFrom: ['lead-agent', 'search-agent'],
    canDelegateTo: ['storage-memory-agent', 'rag-agent'],
    reads: ['postgres', 'llm'],
    writes: ['postgres'],
    history: { ...defaultHistory, maxEntries: 140 },
    responseContract: ['recommended_products', 'ranking_evidence', 'user_fit', 'display_contract'],
    trace: { iconKey: 'sparkles', shortCode: 'R', nodeKind: 'agent' },
  },
  'cart-agent': {
    id: 'cart-agent',
    displayName: 'Cart Agent',
    role: 'Acts as a SQL RAG agent for all cart questions and mutations, including error detection and merged answers.',
    owns: ['cart CRUD', 'cart totals', 'cart item lookup', 'cart operation history'],
    canReceiveFrom: ['lead-agent'],
    canDelegateTo: ['search-agent'],
    reads: ['postgres', 'llm'],
    writes: ['postgres'],
    history: { ...defaultHistory, maxEntries: 160, summarizeAfterEntries: 25 },
    responseContract: ['cart_state', 'operations', 'sql_checks', 'errors', 'lead_response_brief'],
    trace: { iconKey: 'shopping-cart', shortCode: 'C', nodeKind: 'agent' },
  },
  'rag-agent': {
    id: 'rag-agent',
    displayName: 'RAG Agent',
    role: 'Retrieves internal business, legal, support, brand, and product documents with embedding search, Qdrant and rerank.',
    owns: ['business knowledge RAG', 'qdrant retrieval', 'rerank', 'context budget', 'document review'],
    canReceiveFrom: ['lead-agent', 'recommendation-agent', 'customer-support-agent'],
    canDelegateTo: [],
    reads: ['qdrant', 'postgres', 'llm'],
    writes: ['qdrant'],
    history: { ...defaultHistory, maxEntries: 120 },
    responseContract: ['selected_paths', 'reviewed_context', 'token_budget', 'grounded_answer_brief'],
    trace: { iconKey: 'book-open', shortCode: 'KG', nodeKind: 'agent' },
  },
  'security-agent': {
    id: 'security-agent',
    displayName: 'Security Agent',
    role: 'Moderates input, agent outputs, policy risks, prompt injection, and unsafe final responses.',
    owns: ['input guardrail', 'output guardrail', 'tool safety', 'policy refusal'],
    canReceiveFrom: ['lead-agent'],
    canDelegateTo: [],
    reads: ['llm', 'in_memory'],
    writes: ['in_memory'],
    history: { enabled: true, windows: ['recent', 'summary'], maxEntries: 80, summarizeAfterEntries: 20 },
    responseContract: ['risk_level', 'decision', 'complaints', 'safe_instruction'],
    trace: { iconKey: 'shield', shortCode: 'SEC', nodeKind: 'agent' },
  },
  'customer-support-agent': {
    id: 'customer-support-agent',
    displayName: 'Customer Support Agent',
    role: 'Handles defects, returns, complaints, warranty, refund, delivery, and escalation workflows.',
    owns: ['complaints', 'returns', 'warranty', 'support cases', 'escalation'],
    canReceiveFrom: ['lead-agent'],
    canDelegateTo: ['rag-agent', 'security-agent'],
    reads: ['postgres', 'qdrant', 'llm'],
    writes: ['postgres'],
    history: { ...defaultHistory, maxEntries: 120 },
    responseContract: ['support_category', 'policy_evidence', 'case_action', 'customer_reply_brief'],
    trace: { iconKey: 'headphones', shortCode: 'CS', nodeKind: 'agent' },
  },
  'sales-agent': {
    id: 'sales-agent',
    displayName: 'Sales Agent',
    role: 'Turns the lead brief into the final natural customer-facing answer while matching displayed product cards.',
    owns: ['final copy', 'sales framing', 'product-card alignment', 'next best action'],
    canReceiveFrom: ['lead-agent'],
    canDelegateTo: ['security-agent'],
    reads: ['llm', 'in_memory'],
    writes: ['postgres'],
    history: { ...defaultHistory, maxEntries: 140 },
    responseContract: ['final_text', 'product_card_ids', 'quick_replies', 'alignment_checks'],
    trace: { iconKey: 'message-circle', shortCode: 'SA', nodeKind: 'agent' },
  },
};

export function getPipelineV2AgentDefinition(agent: PipelineV2Agent): PipelineV2AgentDefinition {
  return PIPELINE_V2_AGENT_REGISTRY[agent];
}

export function isPipelineV2Agent(value: string): value is PipelineV2Agent {
  return PIPELINE_V2_AGENT_IDS.includes(value as PipelineV2Agent);
}
